name: "Build"

# on:
#   push:
#     branches: [ main ]

on:
  pull_request:
    branches:
      - main

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "Deploy front-end"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: "Deploy to Vercel"
        id: deploy
        run: |
          npx vercel deploy --prod --force --token ${VERCEL_TOKEN} > output.log
          echo ::set-output name=VERCEL_OUTPUT::$(cat output.log)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      - uses: actions/github-script@v6
        name: "Add some comment"
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployed URL: ${{ steps.deploy.outputs.VERCEL_OUTPUT }}'
            })