name: "Deploy"

# on:
#   push:
#     branches: [ main ]

on:
  pull_request:
    branches:
      - main

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "Deploy front-end"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.0

      - uses: actions/github-script@v6
        name: "Add some comment"
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })

      - name: "Deploy to Vercel"
        run: |
          npx vercel --token ${VERCEL_TOKEN} --prod > out.log
          echo xxxxx
          cat out.log
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}