name: "Deploy"

env:
  NODE_VERSION: 16.13.1

on:
  push:
    branches: [ main ]

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "Deploy front-end"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      # - name: "Deploy to Vercel"
      #   run: |
      #     npx vercel --token ${VERCEL_TOKEN} --prod
      #   env:
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}


      - name: 'test env'
        run: |
          echo ${{ env }}
