name: "Deploy"

env:
  FOO: ''

on:
  repository_dispatch:
    types: deploy


jobs:
  vercel:
    name: Deploy ${{ github.event.client_payload.version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'v${{ github.event.client_payload.version }}'

      - name: Deploy ${{ github.event.client_payload.version }}
        run: |
          echo ${{ github.event.client_payload.env }}
          echo ${{ github.event.client_payload.version }}


      - name: Check
        run:
          exit 1