name: "Deploy ${{ github.event.client_payload.version }}"

env:
  NODE_VERSION: 16.13.1

# on:
#   push:
#     branches: [ main ]

on:
  repository_dispatch:
    types: deploy


jobs:
  vercel:
    name: Deploy front-end
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.VERCEL_OUTPUT }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - run: |
          echo ${{ github.event.client_payload.env }}
          echo ${{ github.event.client_payload.version }}

      # - name: "Deploy to Vercel"
      #   id: deploy
      #   run: |
      #     npx vercel deploy --prod --force --token ${VERCEL_TOKEN} > output.log
      #     echo ::set-output name=VERCEL_OUTPUT::$(cat output.log)
      #   env:
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}