name: "Deploy"

on:
  repository_dispatch:
    types: deploy

jobs:
  vercel:
    name: Deploy ${{ github.event.client_payload.version }}
    runs-on: ubuntu-latest
    if: github.event.client_payload.env == 'pre-production'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'v${{ github.event.client_payload.version }}'

      - name: Deploy ${{ github.event.client_payload.version }}
        run: |
          echo ${{ github.event.client_payload.env }}
          echo ${{ github.event.client_payload.version }}

      - name: Prepare env for uat
        if: github.event.client_payload.env == 'uat'
        run: |
          echo "FOO=BAR" >> $GITHUB_ENV

      - name: Prepare env for prod
        run: |
          echo ${{ env.FOO }}
