name: "Deploy"

env:
  DEPLOY_VERSION: 'v${{ github.event.client_payload.version }}'
  DEPLOY_ENV: ${{ github.event.client_payload.env }}

on:
  repository_dispatch:
    types: deploy

jobs:
  vercel:
    name: Deploy ${{ env.DEPLOY_VERSION }}@${{ env.DEPLOY_ENV }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: env.DEPLOY_VERSION

      - name: Deploy ${{ env.DEPLOY_VERSION }}@${{ env.DEPLOY_ENV }}
        run: |
          echo ${{ env.DEPLOY_ENV }}
          echo ${{ env.DEPLOY_VERSION }}

      - name: Prepare env for uat
        if: env.DEPLOY_ENV == 'uat'
        run: |
          echo "FOO=BAR" >> $GITHUB_ENV

      - name: Prepare env for prod
        if: env.DEPLOY_ENV == 'prod'
        run: |
          echo "FOO=XXX" >> $GITHUB_ENV

      - name: Check 1
        if: |
          env.FOO == 'BAR' || env.FOO == 'XXX'
        run: |
          echo ${{ env.FOO }}