name: "Deploy"

on:
  repository_dispatch:
    types: deploy

jobs:
  prepare:
    name: Prepare Deploy ${{ github.event.client_payload.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Payload
        run: |
          echo version=${{ github.event.client_payload.version }}
          echo environment=${{ github.event.client_payload.env }}


  deploy-pre-prod:
    name: Deploy Pre Prod
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: ${{ steps.deploy.outputs.VERCEL_DEPLOY_URL }}
    if: github.event.client_payload.env == 'pre-production'
    needs:
      - prepare
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'v${{ github.event.client_payload.version }}'

      - name: Deploying
        id: deploy
        run: |
          echo ::set-output name=VERCEL_DEPLOY_URL::http://test.cloverink.com

  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: ${{ steps.deploy.outputs.VERCEL_DEPLOY_URL }}
    if: github.event.client_payload.env == 'production'
    needs:
      - prepare
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'v${{ github.event.client_payload.version }}'

      - name: Deploying
        id: deploy
        run: |
          echo ::set-output name=VERCEL_DEPLOY_URL::http://cloverink.com