name: "Deploy"

env:
  NODE_VERSION: 16.13.1

on:
  push:
    branches: [ main ]

jobs:
  vercel:
    name: Deploy front-end
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.VERCEL_OUTPUT }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: "Deploy to Vercel"
        id: deploy
        run: |
          npx vercel deploy --prod --force --token ${VERCEL_TOKEN} > output.log
          echo ::set-output name=VERCEL_OUTPUT::$(cat output.log)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}